[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "DrestryRobot"
authors = [{name = "DrestryRobot", email = "2371478179@qq.com"}]
dynamic = ["version", "description"]
